//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.PROCESS.COMMON.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.PROCESS.COMMON.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #66D181.
        /// </summary>
        public static string ActiveColor {
            get {
                return ResourceManager.GetString("ActiveColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA để được trợ giúp..
        /// </summary>
        public static string CodeError {
            get {
                return ResourceManager.GetString("CodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng định dạng..
        /// </summary>
        public static string EmailErrorMsg {
            get {
                return ResourceManager.GetString("EmailErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên phải kết thúc bằng số..
        /// </summary>
        public static string EmployeeCodeErrorMsg {
            get {
                return ResourceManager.GetString("EmployeeCodeErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được để trống..
        /// </summary>
        public static string EmptyFieldRequireMsg {
            get {
                return ResourceManager.GetString("EmptyFieldRequireMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng kiểm tra lại..
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi nhập liệu vui lòng kiểm tra lại..
        /// </summary>
        public static string InputInValid {
            get {
                return ResourceManager.GetString("InputInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mỗi người dùng phải có ít nhất một vai trò..
        /// </summary>
        public static string NoRole {
            get {
                return ResourceManager.GetString("NoRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #13B2D8.
        /// </summary>
        public static string NotActiveColor {
            get {
                return ResourceManager.GetString("NotActiveColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #616767.
        /// </summary>
        public static string StopActiveColor {
            get {
                return ResourceManager.GetString("StopActiveColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được nhiều hơn {1} kí tự.
        /// </summary>
        public static string TooLongValid {
            get {
                return ResourceManager.GetString("TooLongValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại trong hệ thống..
        /// </summary>
        public static string UniqueErrorMsg {
            get {
                return ResourceManager.GetString("UniqueErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang hoạt động.
        /// </summary>
        public static string UserActive {
            get {
                return ResourceManager.GetString("UserActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa kích hoạt.
        /// </summary>
        public static string UserNotActive {
            get {
                return ResourceManager.GetString("UserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngừng kích hoạt.
        /// </summary>
        public static string UserStopActive {
            get {
                return ResourceManager.GetString("UserStopActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ xác nhận.
        /// </summary>
        public static string UserWaitAcept {
            get {
                return ResourceManager.GetString("UserWaitAcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #F39619.
        /// </summary>
        public static string WaitAceptColor {
            get {
                return ResourceManager.GetString("WaitAceptColor", resourceCulture);
            }
        }
    }
}
